---
- name: Install and start NGINX on RHEL 8.9 servers
  hosts: all
  become: yes
  vars:
    nginx_package: nginx
  tasks:
    # - name: Ensure EPEL repository is enabled (required for nginx on RHEL)
    #   yum:
    #     name: epel-release
    #     state: present

    - name: Install NGINX
      yum:
        name: "{{ nginx_package }}"
        state: present

    - name: Start and enable NGINX service
      systemd:
        name: nginx
        state: started
        enabled: yes
